server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: neosoft@123
  application:
    name: RATING-SERVICE


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true