server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_service
    username: root
    password: neosoft@123

  application:
    name: HOTEL-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

